/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Acer
 * Created: 1-giu-2016
 */
/*
create table utente(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(254),
    cognome VARCHAR(254),
    username VARCHAR(254),
    password VARCHAR(254),
    tipo INTEGER,
    saldo REAL)
*/

select * from letto where nome like '%M%' or descrizione like '%M%';